config/routes.rb
Rails.application.routes.draw do

  resources :users
  get '/signup', to: 'users#new'

  get "/home", to: "pages#home"
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"

  root 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#

class User < ActiveRecord::Base
  attr_accessor :password

  validates :name, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  before_save :encrypt_password


  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end


  private
  def encrypt_password
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    string          #Not the final implementation!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Sign Up"
  end
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Sample Social Network"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  def logo
    image_tag("logo.jpg", alt: "Sample App Logo", class: "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'blueprint/screen', media: 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', media: 'print' %>
  <%= stylesheet_link_tag 'custom', media: 'screen' %>
</head>
<body>
    <div class="container">
      <header>
        <%= link_to logo, root_path %>
        <nav class="round">
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", "#" %></li>
            <li><%= link_to "Sign in", "#" %></li>
          </ul>
        </nav>
      </header>
      <section class="round">
        <%= yield %>
      </section>
      <footer>
        <nav class="round">
          <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
        </nav>
      </footer>
    <%= debug(params) %>

    </div>


</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to "Sign Up Now!", signup_path, class: "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<table class="profile" summary="Profile Information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_image_tag @user.email %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name: </strong><%= @user.name %><br>
      <strong>URL: </strong><%= link_to user_path(@user), user_path(@user) %>
    </td>
  </tr>
</table>